page_layout.condition:
  type: sequence
  sequence:
    type: mapping
    mapping:
      id:
        type: string
        label: 'ID'
      plugin:
        type: string
        label: 'Plugin ID'
      configuration:
        type: ignore
        label: 'Plugin configuration'

page_layout.page.*:
  type: config_object
  label: 'Page Layout definition'
  mapping:
    id:
      type: string
      label: 'ID'
    title:
      type: label
      label: 'Label'
    path:
      type: string
      label: 'Path'
    variants:
      type: sequence
      label: 'Variants'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'ID'
          admin_title:
            type: label
            label: 'Administration title'
          title:
            type: label
            label: 'Title'
          layout:
            type: string
            label: 'Layout'
          conditions:
            type: page_layout.condition
            label: 'Conditions'
          blocks:
            type: ignore
