; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
projects[drupal][version] = "8.1.10"

; Modules
projects[backup_migrate][version] = "4.0-alpha1"

projects[google_analytics][version] = "2.1"

projects[layout_plugin][version] = "1.0-alpha22"
