features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
  logo: true
  name: true
  node_user_picture: 0
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'http://www.linkedin.com/company/zymphonies'
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: rss.xml
copyright_text: 'Copyright 2015· All rights reserved'
show_social_icon: 0
show_credit_link: 1
langcode: da
favicon:
  use_default: 1
  path: ''
