id: node
title: Node
path: /node/%
variants:
  -
    id: 57f63ca9272a1
    admin_title: Article
    title: ''
    layout: kaa_theme.two_column
    conditions:
      -
        id: 57f63cb777827
        plugin: node_type
        configuration:
          bundles:
            article: article
            page: 0
          context_mapping:
            node: '@node.node_route_context:node'
          negate: 0
    blocks:
      1:
        id: 57f6491a146fa
        plugin: 'block_content:738c577e-d951-4744-b900-d8b1b223e012'
        region: left
        weight: '1'
      2:
        id: 59c6c6c40ab7d
        plugin: page_layout_existing_content
        region: left
        weight: '0'
  -
    id: 59c6c6fe0c2be
    admin_title: All
    title: ''
    layout: kaa_theme.two_column
    conditions:
      -
        id: 59c6c70a9f762
        plugin: node_type
        configuration:
          bundles:
            article: article
            page: 0
          context_mapping:
            node: '@node.node_route_context:node'
          negate: 1
    blocks:
      -
        id: 59c6c703a6e1b
        plugin: page_layout_existing_content
        region: left
        weight: '0'
